import { useEffect, useState } from 'react';
import { EMPTY_CLIENT, clientForm, clientPayload } from '../admin-model.js';

export function ClientsPage({ api, report }) {
  const [clients, setClients] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState(EMPTY_CLIENT);
  const load = async () => setClients((await api.clients()).clients);
  useEffect(() => { load().catch(report.error); }, []);
  const change = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const save = async (event) => { event.preventDefault(); try { selected ? await api.updateClient(selected.client_id, clientPayload(form)) : await api.createClient(clientPayload(form)); await load(); report.notice('Client salvato'); } catch (error) { report.error(error); } };
  const remove = async () => { if (!selected || !confirm(`Eliminare ${selected.client_id}?`)) return; try { await api.deleteClient(selected.client_id); setSelected(null); setForm(EMPTY_CLIENT); await load(); report.notice('Client eliminato'); } catch (error) { report.error(error); } };
  return <section className="split"><aside className="panel"><div className="title"><h2>Client</h2><button onClick={() => { setSelected(null); setForm(EMPTY_CLIENT); }}>Nuovo</button></div>{clients.map((client) => <button className={`row ${selected?.client_id === client.client_id ? 'active' : ''}`} key={client.client_id} onClick={() => { setSelected(client); setForm(clientForm(client)); }}><strong>{client.client_id}</strong><small>{client.client_kind}</small></button>)}</aside><form className="panel form" onSubmit={save}><h2>{selected ? 'Modifica client' : 'Nuovo client'}</h2><label>Client ID<input required disabled={Boolean(selected)} value={form.client_id} onChange={change('client_id')} /></label><div className="columns"><label>Tipo<select value={form.client_kind} onChange={change('client_kind')}><option value="browser">browser</option><option value="application">application</option></select></label><label>Autenticazione<select value={form.token_endpoint_auth_method} onChange={change('token_endpoint_auth_method')}><option value="none">none</option><option value="client_secret_post">client_secret_post</option><option value="client_secret_basic">client_secret_basic</option></select></label></div><label>Secret<input type="password" value={form.client_secret} onChange={change('client_secret')} placeholder={selected?.hasSecret ? 'Configurato; lascia vuoto per mantenerlo' : ''} /></label><label>Scope<input value={form.scope} onChange={change('scope')} /></label>{[['grant_types','Grant types'],['response_types','Response types'],['redirect_uris','Redirect URI'],['post_logout_redirect_uris','Post logout URI']].map(([key,label]) => <label key={key}>{label}<textarea rows="3" value={form[key]} onChange={change(key)} /></label>)}<footer><button type="submit">Salva</button>{selected && <button type="button" className="danger" onClick={remove}>Elimina</button>}</footer></form></section>;
}
