import { useEffect, useState } from 'react';
import { EMPTY_USER, userForm } from '../admin-model.js';

export function UsersPage({ api, report }) {
  const [users, setUsers] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState(EMPTY_USER);
  const load = async () => { const result = await api.users(); setUsers(result.users); if (selected) setSelected(result.users.find((item) => item.id === selected.id) || null); };
  useEffect(() => { load().catch(report.error); }, []);
  const choose = (user) => { setSelected(user); setForm(userForm(user)); report.clear(); };
  const change = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const save = async (event) => { event.preventDefault(); report.clear(); try { const body = { ...form }; if (!body.password) delete body.password; selected ? await api.updateUser(selected.id, body) : await api.createUser(body); await load(); report.notice('Utente salvato'); } catch (error) { report.error(error); } };
  const remove = async () => { if (!selected || !confirm(`Eliminare ${selected.username}?`)) return; try { await api.deleteUser(selected.id); setSelected(null); setForm(EMPTY_USER); await load(); report.notice('Utente eliminato'); } catch (error) { report.error(error); } };
  return <section className="split"><aside className="panel"><div className="title"><h2>Utenti</h2><button onClick={() => { setSelected(null); setForm(EMPTY_USER); }}>Nuovo</button></div>{users.map((user) => <button className={`row ${selected?.id === user.id ? 'active' : ''}`} key={user.id} onClick={() => choose(user)}><strong>{user.username}</strong><small>{user.email || user.role}</small></button>)}</aside><form className="panel form" onSubmit={save}><h2>{selected ? 'Modifica utente' : 'Nuovo utente'}</h2><label>Username<input required value={form.username} onChange={change('username')} /></label><label>Email<input type="email" value={form.email || ''} onChange={change('email')} /></label><div className="columns"><label>Nome<input value={form.first_name || ''} onChange={change('first_name')} /></label><label>Cognome<input value={form.last_name || ''} onChange={change('last_name')} /></label></div><div className="columns"><label>Provider<select value={form.auth_provider} onChange={change('auth_provider')}><option value="local">local</option><option value="google">google</option></select></label><label>Ruolo<select value={form.role} onChange={change('role')}><option value="user">user</option><option value="admin">admin</option></select></label></div><div className="columns"><label>Stato<select value={form.status} onChange={change('status')}><option value="active">active</option><option value="disabled">disabled</option></select></label><label>TOTP<select value={form.totp_enabled} onChange={change('totp_enabled')}><option value="0">No</option><option value="1">Sì</option></select></label></div><label>Password<input type="password" minLength="12" required={!selected && form.auth_provider === 'local'} value={form.password} onChange={change('password')} placeholder={selected ? 'Lascia vuoto per non cambiarla' : ''} /></label><footer><button type="submit">Salva</button>{selected && <button type="button" className="danger" onClick={remove}>Elimina</button>}</footer></form></section>;
}
